# This is a GitHub workflow defining a set of jobs with a set of steps. ref:
# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#
# Frigate is a tool for automatically generating documentation for Helm charts.
# We use it to generate the README.md files in the Chart repos from a .frigate
# jinja template file. The jinja template make use of values.yaml and Chart.yaml
# content, so we monitor for changes to those as well as the generated output.
#
# ref: https://github.com/rapidsai/frigate
#
name: Ensure charts' README.md are updated

on:
  pull_request:
    paths:
      - "*/README.md"
      - "*/values.yaml"
      - "*/Chart.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install frigate
        run: |
          python -m pip install --upgrade pip
          pip install frigate

      - name: Check that dask README is up to date
        run: |
          frigate gen dask > dask/README.md
          if git status --porcelain dask/README.md | grep .; then
              echo "README is out of date. Either you have modified README.md directly or you've modified values.yaml or Chart.yaml without generating the README."
              echo "If you have modified with README.md please make those changes in dask/.frigate."
              echo "In both cases please run `frigate gen dask > dask/README.md`."
              exit 1
          fi
      - name: Check that daskhub README is up to date
        run: |
          frigate gen daskhub > daskhub/README.md
          if git status --porcelain daskhub/README.md | grep .; then
              echo "README is out of date. Either you have modified README.md directly or you've modified values.yaml or Chart.yaml without generating the README."
              echo "If you have modified with README.md please make those changes in daskhub/.frigate."
              echo "In both cases please run `frigate gen daskhub > daskhub/README.md`."
              exit 1
          fi
